on: [push]

jobs:
  job_sync:
    runs-on: [self-hosted, Windows]
    env:
       Win_Topaz_Location: ${{ vars.TOPAZ_LOCATION }}
    name: Code Pipeline Sync on self-hosted runners
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Synchronize
        uses: bmc-compuware/ispw-sync-local@v2.0
        id: sync-local
        with:
          host: 'cwcc.bmc.com'
          port: 16196
          uid: 'HAUNXG0'
          pass: ${{ secrets.ISPW_USER_PWD }}
          runtimeConfiguration: 'iccga'
          stream: 'GITFLOW'
          application: 'GITFLOWI'
          subAppl: 'GITFLOWI'
          checkoutLevel: 'FEAT'
          gitUid: '@neilg001abc'
          gitToken: ${{ secrets.NEILG001ABC_GITHUB_TOKEN }}
          gitBranch: "develop"
          gitRepoUrl: "https://github.com/neilg001abc/Demo.git"
          winTopazPath: ${{ vars.TOPAZ_LOCATION }}
          ispwConfigPath: "Demo/GenApp_MainframeCore/ispwconfig.yml"
          assignmentPrefix: "GFLI"
          showEnv: true